
// AUTOMATICALLY GENERATED BY CDK -- DO NOT EDIT
//
#include <cdk/ast/all.h>

#ifdef __NODE_DECLARATIONS_ONLY__

namespace fir {

class address_of_node;
class block_node;
class evaluation_node;
class function_call_node;
class function_declaration_node;
class function_definition_node;
class identity_node;
class if_else_node;
class if_node;
class leave_node;
class null_node;
class pointer_index_node;
class read_node;
class restart_node;
class return_node;
class sizeof_node;
class stack_alloc_node;
class variable_declaration_node;
class while_node;
class writeln_node;
class write_node;


} // namespace fir

#else /* !defined(__NODE_DECLARATIONS_ONLY__) */

#ifndef __AUTOMATIC_fir_NODE_ALLNODES_H__
#define __AUTOMATIC_fir_NODE_ALLNODES_H__

#include "ast/address_of_node.h"
#include "ast/block_node.h"
#include "ast/evaluation_node.h"
#include "ast/function_call_node.h"
#include "ast/function_declaration_node.h"
#include "ast/function_definition_node.h"
#include "ast/identity_node.h"
#include "ast/if_else_node.h"
#include "ast/if_node.h"
#include "ast/leave_node.h"
#include "ast/null_node.h"
#include "ast/pointer_index_node.h"
#include "ast/read_node.h"
#include "ast/restart_node.h"
#include "ast/return_node.h"
#include "ast/sizeof_node.h"
#include "ast/stack_alloc_node.h"
#include "ast/variable_declaration_node.h"
#include "ast/while_node.h"
#include "ast/writeln_node.h"
#include "ast/write_node.h"


#endif /* !defined(__AUTOMATIC_fir_NODE_ALLNODES_H__) */

#endif /* !defined(__NODE_DECLARATIONS_ONLY__) */

